
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: COSC 5P06 - ASSIGNMENT 2.2
description: Discussion on program reading file and sending to server to be threaded and written to a local file